apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ml3tb9c9h-dotnet-basic
  janus-idp.io/tekton: ml3tb9c9h-dotnet-basic
  backstage.io/kubernetes-id: ml3tb9c9h-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ml3tb9c9h-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
